version: "2"

linters:
  enable:
    - bodyclose
    - gocritic
    - misspell
    - revive
    - unconvert
  settings:
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
      disabled-checks:
        - sprintfQuotedString
        - rangeValCopy
        - exitAfterDefer
    revive:
      rules:
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/alvarotorresc/cortex
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
