run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - gocritic
    - revive
    - bodyclose
    - noctx

linters-settings:
  goimports:
    local-prefixes: github.com/alvarotorresc/cortex
  revive:
    rules:
      - name: exported
        severity: warning
      - name: unexported-return
        severity: warning
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
  max-issues-per-linter: 50
  max-same-issues: 3
