// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.4
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CortexPlugin_GetManifest_FullMethodName   = "/cortexplugin.CortexPlugin/GetManifest"
	CortexPlugin_HandleAPI_FullMethodName     = "/cortexplugin.CortexPlugin/HandleAPI"
	CortexPlugin_GetWidgetData_FullMethodName = "/cortexplugin.CortexPlugin/GetWidgetData"
	CortexPlugin_Migrate_FullMethodName       = "/cortexplugin.CortexPlugin/Migrate"
	CortexPlugin_Teardown_FullMethodName      = "/cortexplugin.CortexPlugin/Teardown"
)

// CortexPluginClient is the client API for CortexPlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CortexPluginClient interface {
	GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginManifest, error)
	HandleAPI(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*APIResponse, error)
	GetWidgetData(ctx context.Context, in *WidgetRequest, opts ...grpc.CallOption) (*WidgetData, error)
	Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResult, error)
	Teardown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type cortexPluginClient struct {
	cc grpc.ClientConnInterface
}

func NewCortexPluginClient(cc grpc.ClientConnInterface) CortexPluginClient {
	return &cortexPluginClient{cc}
}

func (c *cortexPluginClient) GetManifest(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginManifest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginManifest)
	err := c.cc.Invoke(ctx, CortexPlugin_GetManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexPluginClient) HandleAPI(ctx context.Context, in *APIRequest, opts ...grpc.CallOption) (*APIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APIResponse)
	err := c.cc.Invoke(ctx, CortexPlugin_HandleAPI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexPluginClient) GetWidgetData(ctx context.Context, in *WidgetRequest, opts ...grpc.CallOption) (*WidgetData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WidgetData)
	err := c.cc.Invoke(ctx, CortexPlugin_GetWidgetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexPluginClient) Migrate(ctx context.Context, in *MigrateRequest, opts ...grpc.CallOption) (*MigrateResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrateResult)
	err := c.cc.Invoke(ctx, CortexPlugin_Migrate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cortexPluginClient) Teardown(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CortexPlugin_Teardown_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CortexPluginServer is the server API for CortexPlugin service.
// All implementations must embed UnimplementedCortexPluginServer
// for forward compatibility.
type CortexPluginServer interface {
	GetManifest(context.Context, *Empty) (*PluginManifest, error)
	HandleAPI(context.Context, *APIRequest) (*APIResponse, error)
	GetWidgetData(context.Context, *WidgetRequest) (*WidgetData, error)
	Migrate(context.Context, *MigrateRequest) (*MigrateResult, error)
	Teardown(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedCortexPluginServer()
}

// UnimplementedCortexPluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCortexPluginServer struct{}

func (UnimplementedCortexPluginServer) GetManifest(context.Context, *Empty) (*PluginManifest, error) {
	return nil, status.Error(codes.Unimplemented, "method GetManifest not implemented")
}
func (UnimplementedCortexPluginServer) HandleAPI(context.Context, *APIRequest) (*APIResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method HandleAPI not implemented")
}
func (UnimplementedCortexPluginServer) GetWidgetData(context.Context, *WidgetRequest) (*WidgetData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWidgetData not implemented")
}
func (UnimplementedCortexPluginServer) Migrate(context.Context, *MigrateRequest) (*MigrateResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Migrate not implemented")
}
func (UnimplementedCortexPluginServer) Teardown(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Teardown not implemented")
}
func (UnimplementedCortexPluginServer) mustEmbedUnimplementedCortexPluginServer() {}
func (UnimplementedCortexPluginServer) testEmbeddedByValue()                      {}

// UnsafeCortexPluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CortexPluginServer will
// result in compilation errors.
type UnsafeCortexPluginServer interface {
	mustEmbedUnimplementedCortexPluginServer()
}

func RegisterCortexPluginServer(s grpc.ServiceRegistrar, srv CortexPluginServer) {
	// If the following call panics, it indicates UnimplementedCortexPluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CortexPlugin_ServiceDesc, srv)
}

func _CortexPlugin_GetManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexPluginServer).GetManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexPlugin_GetManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexPluginServer).GetManifest(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexPlugin_HandleAPI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexPluginServer).HandleAPI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexPlugin_HandleAPI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexPluginServer).HandleAPI(ctx, req.(*APIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexPlugin_GetWidgetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WidgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexPluginServer).GetWidgetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexPlugin_GetWidgetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexPluginServer).GetWidgetData(ctx, req.(*WidgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexPlugin_Migrate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexPluginServer).Migrate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexPlugin_Migrate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexPluginServer).Migrate(ctx, req.(*MigrateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CortexPlugin_Teardown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CortexPluginServer).Teardown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CortexPlugin_Teardown_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CortexPluginServer).Teardown(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CortexPlugin_ServiceDesc is the grpc.ServiceDesc for CortexPlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CortexPlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortexplugin.CortexPlugin",
	HandlerType: (*CortexPluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetManifest",
			Handler:    _CortexPlugin_GetManifest_Handler,
		},
		{
			MethodName: "HandleAPI",
			Handler:    _CortexPlugin_HandleAPI_Handler,
		},
		{
			MethodName: "GetWidgetData",
			Handler:    _CortexPlugin_GetWidgetData_Handler,
		},
		{
			MethodName: "Migrate",
			Handler:    _CortexPlugin_Migrate_Handler,
		},
		{
			MethodName: "Teardown",
			Handler:    _CortexPlugin_Teardown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
